web: bench serve --port 8000
socketio: node apps/frappe/socketio.js
watch: bench watch
schedule: while true; do bench schedule; sleep 60; done
worker: bench worker 1>> logs/worker.log 2>> logs/worker.error.log
